#!/data/data/com.termux/files/usr/bin/bash

SCRIPT_NAME=`basename "$0"`

function init_services {
    echo start sshd...
    busybox start-stop-daemon -n sshd -S -x sshd

    echo start syncthing...
    syncthing -no-browser > ~/syncthing.log 2>&1 &

    echo start shadowsocks...
    startarch sslocal -c $HOME/Shares/private/shadowsocks/config.json > ~/shadowsocks-libev.log 2>&1 &

    echo start privoxy...
    privoxy --no-daemon ~/../usr/etc/privoxy/config > privoxy.log 2>&1 &

    echo start pulseaudio...
    pulseaudio --daemonize=no --exit-idle-time=-1 > pulseaudio.log 2>&1 &

    echo start bad-app-detect job...
    termux-job-scheduler -s ~/bin/bad-apps-detect-wrapper.sh --period-ms 900000 --job-id 1

    echo start run-app-in-container service...
    startarch run-app-in-container-server.fish 9900 > run-app-in-container-service.log 2>&1 &
}

function kill_services {
    echo stop sshd...
    start-stop-daemon -n sshd -K

    echo stop syncthing...
    start-stop-daemon -n syncthing -K

    echo stop shadowsocks...
    #pkill -f -9 shadowsocks-local
    pkill -f -9 sslocal

    echo stop privoxy...
    start-stop-daemon -n privoxy -K

    echo stop pulseaudio...
    pkill -f -9 pulseaudio

    echo stop all jobs...
    termux-job-scheduler --cancel-all

    echo stop run-app-in-container service...
    pkill -f -9 run-app-in-container-server.fish
    pkill -f -9 nc
}

function show_help {
    echo "Usage: $SCRIPT_NAME [-i|-k|-e CMD|-s CMD]"
    exit 1
}

if [[ -z "$1" ]]
then
    show_help
fi

while getopts "ike:s:" o
do
    case $o in
        i) 
            echo start all services
            init_services
            ;;
        k)
            echo stop all services
            kill_services
            ;;
        e)
            echo stop service "$OPTARG"
            start-stop-daemon -n "$OPTARG" -K
            ;;
        s)
            echo start service "$OPTARG"
            start-stop-daemon -b -n "$OPTARG" -S -x "$OPTARG"
            ;;
        ?) 
            show_help
            ;;
    esac
done

