#!/bin/ksh
#
# $OpenBSD: shadowsocks_go.rc,v 1.4 2018/01/11 19:27:10 rpe Exp $

daemon="/home/justin/go/bin/shadowsocks-local"
daemon_flags="-c /home/justin/Shares/private/shadowsocks/config.json"
daemon_user="justin"

. /etc/rc.d/rc.subr

rc_bg=YES

rc_cmd $1
